#include "VirginKeyCodes.h"



VirginKeyCodes::VirginKeyCodes()
{
    _keyMap[CEC::CEC_USER_CONTROL_CODE_PAGE_UP] = "IRCODE CHANNELUP\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_PAGE_DOWN] = "IRCODE CHANNELDOWN\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_CHANNEL_UP] = "IRCODE CHANNELUP\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_CHANNEL_DOWN] = "IRCODE CHANNELDOWN\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_LEFT] = "IRCODE LEFT\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_RIGHT] = "IRCODE RIGHT\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_DOWN] = "IRCODE DOWN\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_UP] = "IRCODE UP\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_SELECT] = "IRCODE SELECT\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_EXIT] = "IRCODE LIVETV\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_NUMBER0] = "IRCODE NUM0\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_NUMBER1] = "IRCODE NUM1\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_NUMBER2] = "IRCODE NUM2\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_NUMBER3] = "IRCODE NUM3\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_NUMBER4] = "IRCODE NUM4\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_NUMBER5] = "IRCODE NUM5\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_NUMBER6] = "IRCODE NUM6\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_NUMBER7] = "IRCODE NUM7\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_NUMBER8] = "IRCODE NUM8\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_NUMBER9] = "IRCODE NUM9\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_RECORD] = "IRCODE RECORD\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_PLAY] = "IRCODE PLAY\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_FAST_FORWARD] = "IRCODE FORWARD\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_REWIND] = "IRCODE REVERSE\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_STOP] = "IRCODE STOP\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_PAUSE] = "IRCODE PAUSE\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_ELECTRONIC_PROGRAM_GUIDE] = "IRCODE GUIDE\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_F1_BLUE] = "IRCODE ACTION_B\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_F2_RED] = "IRCODE ACTION_C\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_F3_GREEN] = "IRCODE GUIDE\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_F4_YELLOW] = "IRCODE RECORD\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_AN_RETURN] = "IRCODE DISPLAY\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_PREVIOUS_CHANNEL] = "IRCODE ENTER\r\n";
    _keyMap[CEC::CEC_USER_CONTROL_CODE_AN_CHANNELS_LIST] = "IRCODE TIVO\r\n";
}

VirginKeyCodes::~VirginKeyCodes()
{
}

const char *VirginKeyCodes::GetIRCode(CEC::cec_user_control_code cecKey)
{
    if (_keyMap.find(cecKey) == _keyMap.end())
        return NULL;

    return _keyMap[cecKey];

}
